# ============================================================
#  Sistema de Turnos - ConfiguraciÃ³n de la aplicaciÃ³n
# ============================================================

# Nombre de la aplicaciÃ³n
spring.application.name=sistema-turnos

# Puerto del servidor
server.port=8080

# ============================================================
#  Conexión MongoDB
# ============================================================
# spring.data.mongodb.uri=mongodb://localhost:27017/turnos_db
spring.data.mongodb.uri=mongodb+srv://user_:database123@cluster0.whoom.mongodb.net/Turnero?appName=Cluster0&connectTimeoutMS=2000&socketTimeoutMS=3000

# ============================================================
#  Logs (opcional - Úil durante desarrollo)

# ============================================================
logging.level.org.springframework.data.mongodb=DEBUG
